### ISSUE TITLE
Interception cache generation error

### ISSUE THREAD

**Issue by maxcamo** [vvasiloud/SortByDate-Magento2#2]
Hello, while doing the Interception cache generation

i see the error

Vvasiloud\SortByDate\Block\Catalog\Product\ProductList\Toolbar
		Incompatible argument type: Required type: \Magento\Catalog\Model\Session. Actual type: array; File:

app/code/Vvasiloud/SortByDate/Block/Catalog/Product/ProductList/Toolbar.php

Total Errors Count: 1

**Comment by vvasiloud** [comment]
Hey sorry for the late reply. 
From the file `Block\Catalog\Product\ProductList\Toolbar` in  `parent::__construct($context, $data)` try passing all the arguments. 
e.g  
`parent::__construct($context, $catalogSession, $catalogConfig, $toolbarModel, $urlEncoder, $productListHelper,$postDataHelper, $data);`

Let me know if this solves the problem.
